language: cpp

dist: focal

cache:
    - pip
before_install:
    - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
    - git fetch origin master
install:
    - sudo bash -c 'echo "deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates universe" >> /etc/apt/sources.list'
    - sudo bash -c 'echo "deb-src http://us.archive.ubuntu.com/ubuntu/ bionic-updates universe" >> /etc/apt/sources.list'
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake
    - cmake --version
    - sudo apt-get install -qq cmake qt5-default
    - pip install cpplint
script:
    - cpplint --filter=-legal/copyright,-readability/todo,-whitespace/line_length,-runtime/threadsafe_fn,-build/header_guard,-build/include_subdir,-whitespace/comments,-whitespace/indent,-readability/alt_tokens --recursive --exclude=third_party/nlohmann/* .
    - cd build/release 
    - cmake -DCMAKE_BUILD_TYPE=Release ../..
    - make -j4
    - cd ../debug
    - cmake -DCMAKE_BUILD_TYPE=Debug ../..
    - make -j4

